schemes:
  cubic:
    name: TCP Cubic
    color: black
    marker: '*'
  bbr:
    name: TCP BBR
    color: gold
    marker: '^'
  pcc:
    name: PCC-Allegro
    color: cyan
    marker: '>'
  verus:
    name: Verus
    color: skyblue
    marker: 'H'
  sprout:
    name: Sprout
    color: orange
    marker: 'p'
  copa:
    name: Copa
    color: red
    marker: 'o'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
  pcc_experimental:
    name: PCC-Expr
    color: olive
    marker: '<'
  indigo:
    name: Indigo
    color: indigo
    marker: 'D'
  fillp_sheep:
    name: FillP-Sheep
    color: violet
    marker: 'D'
  auto_pcc:
    name: AUTO-PCC
    color: red
    marker: 'x'
